/**
 * @description       : 
 * @author            : Surender Patel (Dhruvsoft)
 * @group             : 
 * @last modified on  : 25-05-2021
 * @last modified by  : Surender Patel (Dhruvsoft)
 * Modifications Log 
 * Ver   Date         Author                       Modification
 * 1.0   25-05-2021   Surender Patel (Dhruvsoft)   Initial Version
**/
@IsTest
public class Phoenix_DirectCustomerOfferCtrlTest {

    static testMethod void test1() {
        Phoenix_DirectCustomerOfferCtrl controller = new Phoenix_DirectCustomerOfferCtrl();


    }


}